name: Build and deploy Node.js app to Azure Web App - temrinkwebsite

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Set up Node (no pnpm cache here)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      # (Optional) enable pnpm cache AFTER pnpm is installed
      # - name: Get pnpm store path
      #   run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
      # - uses: actions/cache@v4
      #   with:
      #     path: ${{ env.PNPM_STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      #     restore-keys: ${{ runner.os }}-pnpm-

      - name: Install & build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            .next
            public
            package.json
            next.config.js
            node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: temrinkwebsite
          slot-name: Production
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37F31FD7BF294ED7B4F2D363D96FC5BC }}
